services:
  postgres:
    image: postgres
    container_name: miniapp_pg
    restart: always
    env_file: 
      - .env 
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  miniapp:
    container_name: miniapp
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - miniapp_data:/miniapp

volumes:
  postgres_data:
  miniapp_data: