services:
  postgres:
    image: postgres
    container_name: miniapp_pg
    restart: always
    env_file: 
      - .env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  miniapp:
    container_name: miniapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - miniapp_data:/miniapp

volumes:
  postgres_data:
  miniapp_data: