definitions:
  dto.AuthDTO:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.WebCreateCustomerDTO:
    properties:
      customer_name:
        type: string
      customer_telegram_id:
        type: integer
    type: object
  dto.WebLoadCustomerDTO:
    properties:
      customer_created_at:
        type: string
      customer_id:
        type: integer
      customer_name:
        type: string
      customer_phone_number:
        type: string
      customer_telegram_id:
        type: integer
    type: object
  dto.WebUpdateCustomerDTO:
    properties:
      customer_id:
        type: integer
      customer_name:
        type: string
      customer_phone_number:
        type: string
    type: object
  handlers.Error:
    properties:
      details:
        example: details text
        type: string
      error:
        example: erros text
        type: string
      status:
        example: status text
        type: string
    type: object
  handlers.Result:
    type: object
  handlers.Success:
    properties:
      data:
        $ref: '#/definitions/handlers.Result'
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth:
    post:
      consumes:
      - application/json
      description: Authentification by login and password
      parameters:
      - description: Auth data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.AuthDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Authentification
      tags:
      - Authentification
  /customer:
    get:
      description: Get list of all customers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.WebLoadCustomerDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Get Customer List
      tags:
      - customer
    post:
      consumes:
      - application/json
      description: Create customer
      parameters:
      - description: Customer create data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.WebCreateCustomerDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Create customer
      tags:
      - customer
  /customer/:
    patch:
      consumes:
      - application/json
      description: Update customer by ID
      parameters:
      - description: Customer update data
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/dto.WebUpdateCustomerDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Update customer
      tags:
      - customer
  /customer/{id}:
    get:
      description: Get customers data by id
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.WebLoadCustomerDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.Error'
      summary: Get Customer
      tags:
      - customer
swagger: "2.0"
